# Generated by Django 5.0.7 on 2024-08-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_m', '0003_document_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
    ]
