# Generated by Django 5.0.7 on 2024-08-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_m', '0005_remove_user_created_at_user_date_joined_user_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('ceo', 'CEO'), ('cto', 'CTO'), ('designer', 'Designer'), ('programmer', 'Programmer'), ('product_owner', 'Product Owner'), ('project_owner', 'Project Owner'), ('project_manager', 'Project Manager'), ('qa', 'QA')], default='programmer', max_length=30),
        ),
    ]
